/*
 * This source file was generated by the Gradle 'init' task
 */
package andersen.grdl;

import andersen.grdl.entity.TalkingAnimal;

public class App {
	public static void main(String[] args) {
		System.out.println(TalkingAnimal.talkingCow());
	}
}
